require("denice")

-- [[ Configure and install plugins ]]
-- require("lazy").setup({
	-- "tpope/vim-sleuth", -- Detect tabstop and shiftwidth automatically
	--	{ -- You can easily change to a different colorscheme.
	--		"folke/tokyonight.nvim",
	--		priority = 1000, -- Make sure to load this before all the other start plugins.
	--		init = function()
	--			vim.cmd.colorscheme("tokyonight-night")
	--			vim.cmd.hi("Comment gui=none")
	--		end,
	--	},
-- }, {
-- 	ui = {
-- 		icons = vim.g.have_nerd_font and {} or {
-- 			cmd = "⌘",
-- 			config = "🛠",
-- 			event = "📅",
-- 			ft = "📂",
-- 			init = "⚙",
-- 			keys = "🗝",
-- 			plugin = "🔌",
-- 			runtime = "💻",
-- 			require = "🌙",
-- 			source = "📄",
-- 			start = "🚀",
-- 			task = "📌",
-- 			lazy = "💤 ",
-- 		},
-- 	},
-- })

-- The line beneath this is called `modeline`. See `:help modeline`
-- vim: ts=2 sts=2 sw=2 et
